/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ParserOptions {
  delimiter?: number
  quote?: number
  escape?: number
  hasHeaders?: boolean
  chunkSize?: number
  bufferCapacity?: number
}
export interface ParseResult {
  records: Array<Array<string>>
  isComplete: boolean
}
export declare class CsvParser {
  constructor(options?: ParserOptions | undefined | null)
  parseFileStreaming(path: string, callback: (...args: any[]) => any): void
  parseFile(path: string): Array<Array<string>>
}
